[package]
name = "oxc-toml"
version = "0.14.1"
authors = ["Boshen"]
categories = ["parser-implementations", "parsing"]
edition = "2024"
homepage = "https://github.com/oxc-project/oxc-toml"
keywords = ["toml", "formatter"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/oxc-project/oxc-toml"
description = "A TOML formatter library"

[lib]
test = false

[dependencies]
rowan = "0.16.1"

[dev-dependencies]
walkdir = "2"
